"""changes validation for instructions

Revision ID: 82753346b028
Revises: a09674162c2c
Create Date: 2024-07-07 10:45:15.147749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82753346b028'
down_revision = 'a09674162c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
