"""changes nullable for instr

Revision ID: 90317162786a
Revises: 82753346b028
Create Date: 2024-07-07 10:46:39.017286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90317162786a'
down_revision = '82753346b028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('instructions',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
